default: &default
  adapter: postgresql
  encoding: unicode
  # For details on connection pooling, see Rails configuration guide
  # http://guides.rubyonrails.org/configuring.html#database-pooling
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: civilizations_development
  username: leonelgracia
  password: leonelgracia
  host: localhost
  port: 5432

test:
  <<: *default
  database: civilizations_test
  username: leonelgracia
  password: leonelgracia
  host: localhost
  port: 5432

production:
  <<: *default
  database: d8c6n3paetnfv9
  username: byvnodqrvxghsc
  password: 55161993c5da567a5e7e2491ba8183666eab80959b212d043eac2ff9769ffa70
  host: ec2-52-44-166-58.compute-1.amazonaws.com
  port: 5432
