default: &default
  adapter: postgresql
  encoding: unicode
  # For details on connection pooling, see Rails configuration guide
  # http://guides.rubyonrails.org/configuring.html#database-pooling
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: civilizations_development
  username: leonelgracia
  password: leonelgracia
  host: localhost
  port: 5432

test:
  <<: *default
  database: civilizations_test
  username: leonelgracia
  password: leonelgracia
  host: localhost
  port: 5432

production:
  <<: *default
  database: civilizations_production
  username: civilizations
  password: <%= ENV['CIVILIZATIONS_DATABASE_PASSWORD'] %>
